# generated by fastapi-codegen:
#   filename:  ./openAPI/smartCity.yaml
#   timestamp: 2024-04-21T05:45:43+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class ErrorModel(BaseModel):
    code: int
    message: str


class Camera(BaseModel):
    id: constr(min_length=1) = Field(..., example='int')
    name: constr(min_length=6) = Field(..., example='string')
    latitude: constr(min_length=6) = Field(..., example='string')
    longitude: constr(min_length=6) = Field(..., example='string')
    inService: constr(min_length=4) = Field(..., example='bool')
    streamingUrl: constr(min_length=6) = Field(None, example='string')


class Cameraimage(BaseModel):
    cameraid: constr(min_length=3) = Field(..., example='int')
    timestamp: constr(min_length=6) = Field(..., example='string')
    url: constr(min_length=6) = Field(..., example='string')


class Iotstation(BaseModel):
    id: constr(min_length=3) = Field(..., example='int')
    name: constr(min_length=6) = Field(..., example='string')
    latitude: constr(min_length=6) = Field(..., example='string')
    longitude: constr(min_length=6) = Field(..., example='string')
    stationtype: constr(min_length=6) = Field(..., example='string')


class Iotanalytics(BaseModel):
    iotid: constr(min_length=3) = Field(..., example='int')
    totalflow: constr(min_length=5) = Field(..., example='float')
    avgoccupancy: constr(min_length=5) = Field(..., example='float')
    avgspeed: constr(min_length=5) = Field(..., example='float')
    incidents: constr(min_length=3) = Field(..., example='int')
