# generated by fastapi-codegen:
#   filename:  ./openAPI/smartCity.yaml
#   timestamp: 2024-04-21T21:49:43+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class ErrorModel(BaseModel):
    code: int
    message: str


class Camera(BaseModel):
    id: constr(min_length=1) = Field(..., example='int')
    name: constr(min_length=6) = Field(..., example='string')
    latitude: constr(min_length=6) = Field(..., example='string')
    longitude: constr(min_length=6) = Field(..., example='string')
    inService: constr(min_length=1) = Field(..., example='bool')
    streamingUrl: constr(min_length=0) = Field(None, example='string')


class Cameraimage(BaseModel):
    cameraId: constr(min_length=1) = Field(..., example='int')
    timestamp: constr(min_length=6) = Field(..., example='string')
    url: constr(min_length=0) = Field(None, example='string')


class Iotstation(BaseModel):
    id: constr(min_length=1) = Field(..., example='int')
    name: constr(min_length=1) = Field(..., example='string')
    latitude: constr(min_length=1) = Field(..., example='string')
    longitude: constr(min_length=1) = Field(..., example='string')
    stationType: constr(min_length=2) = Field(..., example='string')


class Iotanalytics(BaseModel):
    iotId: constr(min_length=1) = Field(..., example='int')
    timestamp: constr(min_length=6) = Field(..., example='string')
    totalFlow: constr(min_length=1) = Field(..., example='float')
    avgOccupancy: constr(min_length=0) = Field(..., example='float')
    avgSpeed: constr(min_length=1) = Field(..., example='float')
    incidents: constr(min_length=3) = Field(..., example='int')


class Servicerequest(BaseModel):
    id: constr(min_length=1) = Field(..., example='int')
    date: constr(min_length=6) = Field(..., example='string')
    service: constr(min_length=6) = Field(..., example='string')
    description: constr(min_length=6) = Field(..., example='string')
    deviceType: constr(min_length=6) = Field(..., example='string')
    deviceId: constr(min_length=1) = Field(..., example='int')
